# Site settings
title: Sherry Chou
description: Sherry's personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hsin-Rung (Sherry) Chou
user_description: Hi! My name is Sherry. My works lies at the intersection of Machine Learning, Computer Vision and AR/VR, especially in the application of facial recognition.
                  I graduated with my B.S. in Computer Science from National Tsing-Hua University, and with my M.S. from New York University.
                  I am recently entering the field of Fintech with the title of junior AI scientist.
                  I am a huge fan of The Legend of Zelda.
user_title: Machine Learning / Computer Vision / VR / AR
email: mailto:sherry18030@gmail.com
github_username:  Sherry40931
linkedin_username: hsinrungsherrychou

markdown: kramdown

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
